name: Conventional Commits

on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize
    - reopened

permissions:
  pull-requests: read

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Lint Commits
      uses: wagoid/commitlint-github-action@v6
    - name: Lint Pull Request
      uses: amannn/action-semantic-pull-request@v5.5.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          chore
          vendor
          build
          ci
          revert
          BREAKING

  check_commit_messages:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Commitzen
      run: |
        python -m pip install --upgrade pip
        pip install -U Commitizen

    - name: Check Commit Messages
      run: cz check --rev-range HEAD
