name: Conventional Commits

on:
  pull_request:
    branches:
    - '**'

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
