name: Conventional Commits

on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize
    - reopened

permissions:
  pull-requests: read

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          chore
          vendor
          build
          ci
          revert
          BREAKING

  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Commitlint
      uses: wagoid/commitlint-github-action@v6
