name: Migrate ZenHub Board to GitHub Project

on:
  workflow_dispatch:
    inputs:
      github_org:
        description: "GitHub organization"
        default: "dereksu-org"
        required: true
      github_repo:
        description: "GitHub repository"
        default: "gha-playground"
        required: true
      github_project:
        description: "GitHub project"
        default: "helloworld"
        required: true
jobs:
  sync_zenhub_to_github:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests jq

    - name: Sync ZenHub board to GitHub project
      env:
        ZENHUB_ACCESS_TOKEN: ${{ secrets.ZENHUB_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      run: |
        python ./.github/migrate_zenhub_board_to_github_project.py ${{ inputs.github_org }} ${{ inputs.github_repo }} ${{ inputs.github_project }}
